// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RipetizioniApp.Infrastructure;

#nullable disable

namespace RipetizioniApp.Migrations
{
    [DbContext(typeof(RipetizioniDbContext))]
    [Migration("20260102181458_RichiestaMigration")]
    partial class RichiestaMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RipetizioniApp.Models.Sessioni.Richiesta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdDocente")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdStudente")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdDocente");

                    b.HasIndex("IdStudente");

                    b.ToTable("Richiesta");
                });

            modelBuilder.Entity("RipetizioniApp.Models.Utente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Credenziali", "RipetizioniApp.Models.Utente.Credenziali#Credenziali", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Password");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Username");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Generalita", "RipetizioniApp.Models.Utente.Generalita#Generalita", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Cognome")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Cognome");

                            b1.Property<DateOnly>("DataNascita")
                                .HasColumnType("date")
                                .HasColumnName("Data_Nascita");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Nome");
                        });

                    b.HasKey("Id");

                    b.ToTable("Utente", (string)null);

                    b.HasDiscriminator<string>("Tipo").HasValue("Utente");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RipetizioniApp.Models.Docente", b =>
                {
                    b.HasBaseType("RipetizioniApp.Models.Utente");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CriterioRappresentation", "RipetizioniApp.Models.Docente.CriterioRappresentation#CriterioRappresentation", b1 =>
                        {
                            b1.Property<string>("CriterioPagamento")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CriterioPagamento");

                            b1.Property<int?>("Tariffa")
                                .HasColumnType("integer")
                                .HasColumnName("Tariffa");
                        });

                    b.HasDiscriminator().HasValue("Docente");
                });

            modelBuilder.Entity("RipetizioniApp.Models.Studente", b =>
                {
                    b.HasBaseType("RipetizioniApp.Models.Utente");

                    b.HasDiscriminator().HasValue("Studente");
                });

            modelBuilder.Entity("RipetizioniApp.Models.Sessioni.Richiesta", b =>
                {
                    b.HasOne("RipetizioniApp.Models.Utente", null)
                        .WithMany()
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RipetizioniApp.Models.Utente", null)
                        .WithMany()
                        .HasForeignKey("IdStudente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("RipetizioniApp.Models.Sessioni.ModalitaAccettazione.ModalitaAccettazioneRappresentation", "ModalitaRappresentation", b1 =>
                        {
                            b1.Property<Guid>("RichiestaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Causa")
                                .HasColumnType("text")
                                .HasColumnName("Causa");

                            b1.Property<string>("Modalita")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Modalita");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Status");

                            b1.HasKey("RichiestaId");

                            b1.ToTable("Richiesta");

                            b1.WithOwner()
                                .HasForeignKey("RichiestaId");

                            b1.OwnsOne("RipetizioniApp.Models.MetodoPagamentoRappresentation", "MetodoPagamentoAccettato", b2 =>
                                {
                                    b2.Property<Guid>("ModalitaAccettazioneRappresentationRichiestaId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("MetodoPagamento")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("MetodoPagamentoAccettato");

                                    b2.Property<int>("Tariffa")
                                        .HasColumnType("integer")
                                        .HasColumnName("TariffaAccettata");

                                    b2.HasKey("ModalitaAccettazioneRappresentationRichiestaId");

                                    b2.ToTable("Richiesta");

                                    b2.WithOwner()
                                        .HasForeignKey("ModalitaAccettazioneRappresentationRichiestaId");
                                });

                            b1.OwnsOne("RipetizioniApp.Models.MetodoPagamentoRappresentation", "MetodoPagamentoProposto", b2 =>
                                {
                                    b2.Property<Guid>("ModalitaAccettazioneRappresentationRichiestaId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("MetodoPagamento")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("MetodoPagamentoProposto");

                                    b2.Property<int>("Tariffa")
                                        .HasColumnType("integer")
                                        .HasColumnName("TariffaProposta");

                                    b2.HasKey("ModalitaAccettazioneRappresentationRichiestaId");

                                    b2.ToTable("Richiesta");

                                    b2.WithOwner()
                                        .HasForeignKey("ModalitaAccettazioneRappresentationRichiestaId");
                                });

                            b1.Navigation("MetodoPagamentoAccettato");

                            b1.Navigation("MetodoPagamentoProposto");
                        });

                    b.Navigation("ModalitaRappresentation")
                        .IsRequired();
                });

            modelBuilder.Entity("RipetizioniApp.Models.Docente", b =>
                {
                    b.OwnsOne("RipetizioniApp.Models.ListaMaterie", "Materie", b1 =>
                        {
                            b1.Property<Guid>("DocenteId")
                                .HasColumnType("uuid");

                            b1.HasKey("DocenteId");

                            b1.ToTable("Utente");

                            b1.WithOwner()
                                .HasForeignKey("DocenteId");

                            b1.OwnsMany("RipetizioniApp.Models.Materia", "Lista", b2 =>
                                {
                                    b2.Property<Guid>("DocenteId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Nome")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("Nome");

                                    b2.HasKey("DocenteId", "Id");

                                    b2.ToTable("Materia");

                                    b2.WithOwner()
                                        .HasForeignKey("DocenteId");
                                });

                            b1.Navigation("Lista");
                        });

                    b.Navigation("Materie")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
